# -*- coding: utf-8 -*-
"""l01c01_introduction_to_colab_and_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb

##### Copyright 2018 The TensorFlow Authors.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

x = np.arange(0,10)
y=np.arange(11,21)
y

plt.plot(x,y,'go--',linewidth=1,markersize=12)
plt.title('Line PLot')
plt.xlabel('x-axis')
plt.ylabel('y-axis')

x =np.arange(1,11)
y = 3*x+5
plt.title('Line chart')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.plot(x,y)

x = np.arange(0,4*np.pi,0.1)
y = np.sin(x)
plt.title('sine wave form')
plt.plot(x,y,color ='c')
plt.show()

x=np.arange(0,9)
y=x*x
plt.xlabel('x-axis',color='blue')
plt.ylabel('y-axis',color='blue')
plt.plot(x,y,color='r')
plt.show()

plt.subplot(2,2,1)
plt.plot(x,y,'r--')
plt.subplot(2,2,2)
plt.plot(x,y,'go')

x = [1,2,3,4,5,6,7]
y = [160,150,140,145,175,165,180]
plt.title('Sales vs days')
plt.xlabel('days of the week',color='b')
plt.ylabel('sales',color='b')
plt.plot(x,y)
plt.show()